CMTPATH=/gpfs/fs03/t2k/beam/work/nchikuma
CMT_tag=$(tag)
CMTROOT=/gpfs/fs03/t2k/beam/work/nchikuma/CMT/v1r20p20081118
CMT_root=/gpfs/fs03/t2k/beam/work/nchikuma/CMT/v1r20p20081118
CMTVERSION=v1r20p20081118
CMT_cmtpath=/gpfs/fs03/t2k/beam/work/nchikuma
CMT_project=work
CMT_project_release=nchikuma
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=${ONLINEMONMAINROOT}/${onlineMonMain_tag}:/gpfs/fs03/t2k/beam/work/nchikuma/oaRawEvent/v3r5/amd64_linux26:/gpfs/fs03/t2k/beam/work/nchikuma/oaEvent/v7r3/amd64_linux26:/gpfs/fs03/t2k/beam/work/nchikuma/ROOT/v5r24p00n02/amd64_linux26/bin:/gpfs/fs03/t2k/beam/work/nchikuma/MYSQL/v5r051a/amd64_linux26/bin:/gpfs/fs03/t2k/beam/work/nchikuma/nd280Policy/v2r21/scripts:/gpfs/fs03/t2k/beam/work/nchikuma/CMT/v1r20p20081118/${CMTBIN}:/:/gpfs/fs03/t2k/beam/work/tatsuya1/INGRID/basesoft/CLHEP/v2r0p3/amd64_linux26/bin:/gpfs/fs03/t2k/beam/work/nchikuma/EXTERN/v3r8/scripts:/gpfs/fs03/t2k/beam/work/nchikuma/GSL/v1r15p0n00/amd64_linux26/bin:/gpfs/fs03/t2k/beam/work/tatsuya1/INGRID/basesoft/GEANT/v9r2p01n00/amd64_linux26:/home/t2k/tatsuya1/cern/cernlib/2006/bin:/gpfs/fs03/t2k/beam/work/nchikuma/script:/opt/texlive/2015/bin/x86_64-linux:/usr/lib64/qt-3.3/bin:/opt/lsf/latest/linux2.6-glibc2.3-x86_64/etc:/opt/lsf/latest/linux2.6-glibc2.3-x86_64/bin:/opt/allinea/forge/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/cern/pro/bin:/opt/local/bin:/home/t2k/nchikuma/procmail/bin:/home/t2k/nchikuma/bin:/gpfs/fs03/t2k/beam/work/nchikuma/EXTERN/v3r1/scripts:/gpfs/fs03/t2k/beam/work/nchikuma/testBase/v1r5/amd64_linux26:/gpfs/fs03/t2k/beam/work/nchikuma/testBase/v1r5/scripts:/gpfs/fs03/t2k/beam/work/nchikuma/oaEvent/v7r3/scripts
CLASSPATH=/gpfs/fs03/t2k/beam/work/nchikuma/CMT/v1r20p20081118/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags=-g -pipe -O0 -Wall -ansi -Wctor-dtor-privacy -Wnon-virtual-dtor -fpic 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=lockfile 
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc67-gcc447
INGRID_tag=$(tag)
INGRIDROOT=/gpfs/fs03/t2k/beam/work/nchikuma/B2/b2_software/INGRID/INGRID/v1r1
INGRID_root=/gpfs/fs03/t2k/beam/work/nchikuma/B2/b2_software/INGRID/INGRID/v1r1
INGRIDVERSION=v1r1
INGRID_cmtpath=/gpfs/fs03/t2k/beam/work/nchikuma
INGRID_offset=B2/b2_software/INGRID
INGRID_project=work
INGRID_project_release=nchikuma
nd280Policy_tag=$(tag)
ND280POLICYROOT=/gpfs/fs03/t2k/beam/work/nchikuma/nd280Policy/v2r21
nd280Policy_root=/gpfs/fs03/t2k/beam/work/nchikuma/nd280Policy/v2r21
ND280POLICYVERSION=v2r21
nd280Policy_cmtpath=/gpfs/fs03/t2k/beam/work/nchikuma
nd280Policy_project=work
nd280Policy_project_release=nchikuma
ROOT_tag=$(tag)
ROOTROOT=/gpfs/fs03/t2k/beam/work/nchikuma/ROOT/v5r24p00n02
ROOT_root=/gpfs/fs03/t2k/beam/work/nchikuma/ROOT/v5r24p00n02
ROOTVERSION=v5r24p00n02
ROOT_cmtpath=/gpfs/fs03/t2k/beam/work/nchikuma
ROOT_project=work
ROOT_project_release=nchikuma
EXTERN_tag=$(tag)
EXTERNROOT=/gpfs/fs03/t2k/beam/work/nchikuma/EXTERN/v3r1
EXTERN_root=/gpfs/fs03/t2k/beam/work/nchikuma/EXTERN/v3r1
EXTERNVERSION=v3r1
EXTERN_cmtpath=/gpfs/fs03/t2k/beam/work/nchikuma
EXTERN_project=work
EXTERN_project_release=nchikuma
MYSQL_tag=$(tag)
MYSQLROOT=/gpfs/fs03/t2k/beam/work/nchikuma/MYSQL/v5r051a
MYSQL_root=/gpfs/fs03/t2k/beam/work/nchikuma/MYSQL/v5r051a
MYSQLVERSION=v5r051a
MYSQL_cmtpath=/gpfs/fs03/t2k/beam/work/nchikuma
MYSQL_project=work
MYSQL_project_release=nchikuma
LD_LIBRARY_PATH=${ONLINEMONMAINROOT}/${onlineMonMain_tag}:/gpfs/fs03/t2k/beam/work/nchikuma/oaRawEvent/v3r5/amd64_linux26:/gpfs/fs03/t2k/beam/work/nchikuma/oaEvent/v7r3/amd64_linux26:/gpfs/fs03/t2k/beam/work/nchikuma/ROOT/v5r24p00n02/amd64_linux26/lib/root:/gpfs/fs03/t2k/beam/work/nchikuma/MYSQL/v5r051a/amd64_linux26/lib/mysql:/:/gpfs/fs03/t2k/beam/work/tatsuya1/INGRID/basesoft/CLHEP/v2r0p3/amd64_linux26/lib:/gpfs/fs03/t2k/beam/work/nchikuma/GSL/v1r15p0n00/amd64_linux26/lib:/gpfs/fs03/t2k/beam/work/tatsuya1/INGRID/basesoft/GEANT/v9r2p01n00/amd64_linux26/Linux-g++:/gpfs/fs03/t2k/beam/work/tatsuya1/INGRID/basesoft/GEANT/v9r2p01n00/amd64_linux26/plists/Linux-g++:/home/t2k/tatsuya1/cern/cernlib/2006/lib:/opt/lsf/latest/linux2.6-glibc2.3-x86_64/lib
MYSQL_BASE_DIR=/gpfs/fs03/t2k/beam/work/nchikuma/MYSQL/v5r051a/amd64_linux26
MYSQL_LIB_DIR=${MYSQL_BASE_DIR}/lib/mysql
MYSQL_INCLUDE_DIR=${MYSQL_BASE_DIR}/include/mysql
MAKFLAGS=--no-print-directory
ROOT_PATH=$(ROOTROOT)/$(tag)
ROOT_BIN=$(ROOT_PATH)/bin
ROOT_LIB=$(ROOT_PATH)/lib/root
ROOTSYS=/gpfs/fs03/t2k/beam/work/nchikuma/ROOT/v5r24p00n02/amd64_linux26
PYTHONPATH=${ROOTSYS}/lib/root
ROOT_linkopts=`$(ROOT_BIN)/root-config --glibs` -L/gpfs/fs03/t2k/beam/work/nchikuma/B2/b2_software/lib -lEVENTSUMMARY -lHitSummary -lSimHitSummary -lSimVertexSummary -lSimParticleSummary -lBeamInfoSummary -lBasicReconSummary -lFirstReducSummary -lNeutInfoSummary -lTrackSummary -lThreeDimReconSummary -lTwoDimReconSummary -lSpectrum -lEG -lGeom -lMinuit -lFumili  -lXMLParser -lXMLParser
ROOT_cppflags=-DROOT_USED `$(ROOT_BIN)/root-config --cflags` -Wno-long-long
ROOT_stamps=$(ROOTROOT)/$(ROOTCONFIG)/ROOT.stamp
dict=../dict/
rootcint=$(ROOT_BIN)/rootcint
oaEvent_tag=$(tag)
OAEVENTROOT=/gpfs/fs03/t2k/beam/work/nchikuma/oaEvent/v7r3
oaEvent_root=/gpfs/fs03/t2k/beam/work/nchikuma/oaEvent/v7r3
OAEVENTVERSION=v7r3
oaEvent_cmtpath=/gpfs/fs03/t2k/beam/work/nchikuma
oaEvent_project=work
oaEvent_project_release=nchikuma
testBase_tag=$(tag)
TESTBASEROOT=/gpfs/fs03/t2k/beam/work/nchikuma/testBase/v1r5
testBase_root=/gpfs/fs03/t2k/beam/work/nchikuma/testBase/v1r5
TESTBASEVERSION=v1r5
testBase_cmtpath=/gpfs/fs03/t2k/beam/work/nchikuma
testBase_project=work
testBase_project_release=nchikuma
testBase_cppflags= -DTESTBASE_USED 
oaEvent_cppflags= -DOAEVENT_USED 
oaEvent_linkopts= -L$(OAEVENTROOT)/$(oaEvent_tag) -loaEvent 
oaEvent_stamps= $(OAEVENTROOT)/$(oaEvent_tag)/oaEvent.stamp
oaRawEvent_tag=$(tag)
OARAWEVENTROOT=/gpfs/fs03/t2k/beam/work/nchikuma/oaRawEvent/v3r5
oaRawEvent_root=/gpfs/fs03/t2k/beam/work/nchikuma/oaRawEvent/v3r5
OARAWEVENTVERSION=v3r5
oaRawEvent_cmtpath=/gpfs/fs03/t2k/beam/work/nchikuma
oaRawEvent_project=work
oaRawEvent_project_release=nchikuma
oaRawEvent_cppflags= -DOARAWEVENT_USED 
oaRawEvent_linkopts= -L$(OARAWEVENTROOT)/$(oaRawEvent_tag) -loaRawEvent 
oaRawEvent_stamps= $(OARAWEVENTROOT)/$(oaRawEvent_tag)/oaRawEvent.stamp
onlineMonMain_cppflags= -DONLINEMONMAIN_USED 
onlineMonMain_linkopts= -L$(ONLINEMONMAINROOT)/$(onlineMonMain_tag) -lonlineMonMain 
onlineMonMain_stamps= $(ONLINEMONMAINROOT)/$(onlineMonMain_tag)/onlineMonMain.stamp
tag=amd64_linux26
package=INGRID
version=v1r1
PACKAGE_ROOT=$(INGRIDROOT)
srcdir=../src
bin=../$(INGRID_tag)/
BIN=/gpfs/fs03/t2k/beam/work/nchikuma/B2/b2_software/INGRID/INGRID/v1r1/$(INGRID_tag)/
javabin=../classes/
mgrdir=cmt
project=work
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin
use_linkopts= $(cmt_installarea_linkopts)   $(INGRID_linkopts)  $(oaRawEvent_linkopts)  $(oaEvent_linkopts)  $(ROOT_linkopts)  $(MYSQL_linkopts)  $(EXTERN_linkopts)  $(testBase_linkopts)  $(nd280Policy_linkopts) 
work_installarea_prefix=$(cmt_installarea_prefix)
work_installarea_prefix_remove=$(work_installarea_prefix)
use_requirements=requirements $(CMTROOT)/mgr/requirements $(OARAWEVENTROOT)/cmt/requirements $(OAEVENTROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(MYSQLROOT)/cmt/requirements $(EXTERNROOT)/cmt/requirements $(TESTBASEROOT)/cmt/requirements $(ND280POLICYROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(oaRawEvent_root)/src" $(ppcmd)"$(oaEvent_root)/src" $(ppcmd)"/gpfs/fs03/t2k/beam/work/nchikuma/ROOT/v5r24p00n02/amd64_linux26/include/root" $(ppcmd)"none" $(ppcmd)"/gpfs/fs03/t2k/beam/work/nchikuma/MYSQL/v5r051a/amd64_linux26/include/mysql" $(ppcmd)"$(EXTERN_root)/src" $(ppcmd)"$(testBase_root)/src" $(ppcmd)"$(nd280Policy_root)/src" 
use_fincludes= $(use_includes)
use_stamps= $(INGRID_stamps)  $(oaRawEvent_stamps)  $(oaEvent_stamps)  $(ROOT_stamps)  $(MYSQL_stamps)  $(EXTERN_stamps)  $(testBase_stamps)  $(nd280Policy_stamps) 
use_cflags=  $(INGRID_cflags)  $(oaRawEvent_cflags)  $(oaEvent_cflags)  $(ROOT_cflags)  $(MYSQL_cflags)  $(EXTERN_cflags)  $(testBase_cflags)  $(nd280Policy_cflags) 
use_pp_cflags=  $(INGRID_pp_cflags)  $(oaRawEvent_pp_cflags)  $(oaEvent_pp_cflags)  $(ROOT_pp_cflags)  $(MYSQL_pp_cflags)  $(EXTERN_pp_cflags)  $(testBase_pp_cflags)  $(nd280Policy_pp_cflags) 
use_cppflags=  $(INGRID_cppflags)  $(oaRawEvent_cppflags)  $(oaEvent_cppflags)  $(ROOT_cppflags)  $(MYSQL_cppflags)  $(EXTERN_cppflags)  $(testBase_cppflags)  $(nd280Policy_cppflags) 
use_pp_cppflags=  $(INGRID_pp_cppflags)  $(oaRawEvent_pp_cppflags)  $(oaEvent_pp_cppflags)  $(ROOT_pp_cppflags)  $(MYSQL_pp_cppflags)  $(EXTERN_pp_cppflags)  $(testBase_pp_cppflags)  $(nd280Policy_pp_cppflags) 
use_fflags=  $(INGRID_fflags)  $(oaRawEvent_fflags)  $(oaEvent_fflags)  $(ROOT_fflags)  $(MYSQL_fflags)  $(EXTERN_fflags)  $(testBase_fflags)  $(nd280Policy_fflags) 
use_pp_fflags=  $(INGRID_pp_fflags)  $(oaRawEvent_pp_fflags)  $(oaEvent_pp_fflags)  $(ROOT_pp_fflags)  $(MYSQL_pp_fflags)  $(EXTERN_pp_fflags)  $(testBase_pp_fflags)  $(nd280Policy_pp_fflags) 
use_libraries= $(oaRawEvent_libraries)  $(oaEvent_libraries)  $(ROOT_libraries)  $(MYSQL_libraries)  $(EXTERN_libraries)  $(testBase_libraries)  $(nd280Policy_libraries) 
includes= $(ppcmd)"$(srcdir)" $(use_includes)
fincludes= $(includes)
DSTMaker_use_linkopts=  $(INGRID_linkopts)  $(oaRawEvent_linkopts)  $(oaEvent_linkopts)  $(ROOT_linkopts)  $(MYSQL_linkopts)  $(EXTERN_linkopts)  $(testBase_linkopts)  $(nd280Policy_linkopts) 
Calc_MPPC_new_use_linkopts=  $(INGRID_linkopts)  $(oaRawEvent_linkopts)  $(oaEvent_linkopts)  $(ROOT_linkopts)  $(MYSQL_linkopts)  $(EXTERN_linkopts)  $(testBase_linkopts)  $(nd280Policy_linkopts) 
constituents= dictionary version register DSTMaker Calc_MPPC_new 
all_constituents= $(constituents)
constituentsclean= Calc_MPPC_newclean DSTMakerclean registerclean versionclean dictionaryclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
documentation_constituents= doxygen 
documentation_constituentsclean= doxygenclean 
